import logging
import random
import smtplib
import string
import time
import unicodedata
from dataclasses import dataclass
from enum import Enum

import dns.resolver

logger = logging.getLogger(__name__)


def strip_accents(text: str) -> str:
    """Remove accents/diacritics from a string (e.g. "Élodie" -> "Elodie")."""
    return "".join(c for c in unicodedata.normalize("NFD", text) if unicodedata.category(c) != "Mn")


def generate_candidates(prenom: str, nom: str, domain: str) -> list[str]:
    """
    Generate a list of possible email candidates based on the given first name, last name, and domain.

    Args:
        prenom (str): The first name of the person.
        nom (str): The last name of the person.
        domain (str): The domain of the email address.

    Returns:
        list[str]: A list of possible email candidates.
    """
    prenom = strip_accents(prenom).lower().replace(" ", "").replace("-", "")
    nom = strip_accents(nom).lower().replace(" ", "").replace("-", "")
    candidates = []

    # Common email formats
    candidates.append(f"{prenom}.{nom}@{domain}")
    candidates.append(f"{prenom}{nom}@{domain}")
    candidates.append(f"{prenom[0]}{nom}@{domain}")
    candidates.append(f"{prenom}{nom[0]}@{domain}")
    candidates.append(f"{prenom[0]}.{nom}@{domain}")
    candidates.append(f"{prenom}.{nom[0]}@{domain}")
    candidates.append(f"{prenom}@{domain}")
    candidates.append(f"{nom}@{domain}")

    return candidates


class SmtpStatus(str, Enum):
    DELIVERABLE = "deliverable"
    CATCH_ALL = "catch_all"
    UNDELIVERABLE = "undeliverable"
    UNKNOWN = "unknown"


SMTP_STATUS_SCORES: dict[SmtpStatus, int] = {
    SmtpStatus.DELIVERABLE: 95,
    SmtpStatus.CATCH_ALL: 40,
    SmtpStatus.UNDELIVERABLE: 0,
    SmtpStatus.UNKNOWN: 20,
}


def verify_smtp(email: str, from_address: str = "verify@example.com", timeout: float = 10.0) -> SmtpStatus:
    """
    Verify if the given email address is accepted by its mail server, without sending any message.

    Resolves the domain's MX record, then opens a single SMTP session to run HELO/MAIL FROM/RCPT TO
    (no DATA is ever sent). A random address is probed first to detect catch-all domains, since a
    catch-all server accepts any RCPT TO and makes per-address verification meaningless.

    Args:
        email (str): The email address to verify.
        from_address (str): The address used for the SMTP MAIL FROM step.
        timeout (float): Socket timeout in seconds for the SMTP session.

    Returns:
        SmtpStatus: DELIVERABLE if the address was individually accepted, CATCH_ALL if the domain
            accepts any address, UNDELIVERABLE if the address was rejected, UNKNOWN on any error
            (e.g. no MX record, connection failure, timeout).
    """
    start = time.monotonic()
    try:
        domain = email.split('@')[1]
        records = sorted(dns.resolver.resolve(domain, 'MX'), key=lambda r: r.preference)
        mx_host = records[0].exchange.to_text().rstrip('.')
        logger.info("verify_smtp(%s): MX=%s", email, mx_host)

        random_local = ''.join(random.choices(string.ascii_lowercase, k=16))
        random_address = f"{random_local}@{domain}"

        smtp = smtplib.SMTP(timeout=timeout)
        try:
            smtp.connect(mx_host)
            smtp.helo(from_address.split('@')[1])
            smtp.mail(from_address)

            catch_all_code, _ = smtp.rcpt(random_address)
            logger.info("verify_smtp(%s): catch-all probe -> %s", email, catch_all_code)
            if catch_all_code in (250, 251):
                logger.info("verify_smtp(%s) = CATCH_ALL (%.2fs)", email, time.monotonic() - start)
                return SmtpStatus.CATCH_ALL

            exists_code, _ = smtp.rcpt(email)
            logger.info("verify_smtp(%s): rcpt probe -> %s", email, exists_code)
            if exists_code in (250, 251):
                logger.info("verify_smtp(%s) = DELIVERABLE (%.2fs)", email, time.monotonic() - start)
                return SmtpStatus.DELIVERABLE
            logger.info("verify_smtp(%s) = UNDELIVERABLE (%.2fs)", email, time.monotonic() - start)
            return SmtpStatus.UNDELIVERABLE
        finally:
            try:
                smtp.quit()
            except Exception:
                smtp.close()
    except Exception as e:
        logger.warning("verify_smtp(%s) = UNKNOWN after %.2fs: %s", email, time.monotonic() - start, e)
        return SmtpStatus.UNKNOWN


@dataclass
class FoundEmail:
    email: str
    status: SmtpStatus
    score: int


def find_email(domain: str, prenom: str, nom: str, **_) -> FoundEmail | None:
    """
    Guess and verify the professional email address of a person at the given domain.

    Tries each candidate generated by `generate_candidates` in turn and stops at the first one
    verified deliverable. A candidate found catch-all is returned immediately too, since a
    catch-all result is a property of the domain and would be identical for every other candidate.
    Undeliverable candidates are skipped in favor of the next one; if nothing better is found, the
    first candidate whose status could not be determined (UNKNOWN) is returned as a fallback.

    Args:
        domain (str): The domain of the email address.
        prenom (str): The first name of the person.
        nom (str): The last name of the person.

    Returns:
        FoundEmail | None: The best candidate found with its SMTP status and confidence score, or
            None if every candidate was verified undeliverable.
    """
    fallback: FoundEmail | None = None
    candidates = generate_candidates(prenom, nom, domain)
    logger.info("find_email(domain=%s, prenom=%s, nom=%s): %d candidats à tester", domain, prenom, nom, len(candidates))

    for candidate in candidates:
        status = verify_smtp(candidate)

        if status in (SmtpStatus.DELIVERABLE, SmtpStatus.CATCH_ALL):
            logger.info("find_email: retenu %s (%s)", candidate, status)
            return FoundEmail(email=candidate, status=status, score=SMTP_STATUS_SCORES[status])

        if status == SmtpStatus.UNKNOWN and fallback is None:
            fallback = FoundEmail(email=candidate, status=status, score=SMTP_STATUS_SCORES[status])

    if fallback:
        logger.info("find_email: fallback UNKNOWN sur %s", fallback.email)
    else:
        logger.info("find_email: aucun candidat déliverable pour %s/%s@%s", prenom, nom, domain)
    return fallback
